import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/global/Footer";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/provider/provider";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${montserrat.className} antialiased overflow-x-hidden`}
      >
        <main className="flex flex-col">
          <QueryProvider>{children}</QueryProvider>

          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
